//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBCloning.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("app")]
        public string PathBasedHost {
            get {
                return ((string)(this["PathBasedHost"]));
            }
            set {
                this["PathBasedHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("devops.lab.com")]
        public string CloudHost {
            get {
                return ((string)(this["CloudHost"]));
            }
            set {
                this["CloudHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MySQL")]
        public string SnapPlugin {
            get {
                return ((string)(this["SnapPlugin"]));
            }
            set {
                this["SnapPlugin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://10.192.39.22:8146")]
        public string SnapCenterUrl {
            get {
                return ((string)(this["SnapCenterUrl"]));
            }
            set {
                this["SnapCenterUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LAB\\\\Administrator")]
        public string SnapCenterAdmin {
            get {
                return ((string)(this["SnapCenterAdmin"]));
            }
            set {
                this["SnapCenterAdmin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Netapp!2")]
        public string SnapCenterPassword {
            get {
                return ((string)(this["SnapCenterPassword"]));
            }
            set {
                this["SnapCenterPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("apprendadb")]
        public string SnapDBName {
            get {
                return ((string)(this["SnapDBName"]));
            }
            set {
                this["SnapDBName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("app-linux2.lab.com")]
        public string SnapDBHost {
            get {
                return ((string)(this["SnapDBHost"]));
            }
            set {
                this["SnapDBHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mysql_ondemand")]
        public string SnapPolicy {
            get {
                return ((string)(this["SnapPolicy"]));
            }
            set {
                this["SnapPolicy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/var/lib/start-mysql.sh")]
        public string SnapMountScript {
            get {
                return ((string)(this["SnapMountScript"]));
            }
            set {
                this["SnapMountScript"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.192.39.71")]
        public string SnapDataLeafIP {
            get {
                return ((string)(this["SnapDataLeafIP"]));
            }
            set {
                this["SnapDataLeafIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/var/lib/mysql2")]
        public string SnapMountPath {
            get {
                return ((string)(this["SnapMountPath"]));
            }
            set {
                this["SnapMountPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("app-linux1.lab.com")]
        public string SnapDBCloneHost {
            get {
                return ((string)(this["SnapDBCloneHost"]));
            }
            set {
                this["SnapDBCloneHost"] = value;
            }
        }
    }
}
